services:
  - type: web
    name: creatilink-api
    runtime: docker
    repo: https://github.com/valentino2805/CreatiLink-platform
    branch: main
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
