#@CreatiLink_platform_HostAddress = http://localhost:5173

#GET {{CreatiLink_platform_HostAddress}}/weatherforecast/
#Accept: application/json

###

@CreatiLink_platform_HostAddress = https://creatilink-backend.up.railway.app
GET {{CreatiLink_platform_HostAddress}}/weatherforecast/
